// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1600970961);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1600971992);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1600970721);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1600970841);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.amount_written", 1018);
user_pref("browser.cache.disk.capacity", 337920);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.search.region", "US");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Tue, 22 Sep 2020 11:07:55 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1600970961);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200629235513");
user_pref("extensions.lastAppVersion", "68.10.0");
user_pref("extensions.lastPlatformVersion", "68.10.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"ffc77e60-83dd-42a7-860a-bcba5bd8e854\",\"default-theme@mozilla.org\":\"a6c4e8c9-7e8f-4fea-b608-835077587858\",\"google@search.mozilla.org\":\"c6e2da3b-3a69-4b14-82a0-abdca83b9bd6\",\"amazondotcom@search.mozilla.org\":\"629c3738-68f5-43a7-84cd-fd077905322e\",\"bing@search.mozilla.org\":\"401e4586-a91f-47ed-a72d-c9220d1db166\",\"ddg@search.mozilla.org\":\"4822eb77-7e05-420a-8323-9d9d6aa48f40\",\"twitter@search.mozilla.org\":\"37c1159d-ad8b-4d47-9442-99ea38a7c64f\",\"wikipedia@search.mozilla.org\":\"462a4120-e8b8-4cce-9e10-1e9eca8c10e6\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "45ba3875-8f60-4bd9-b554-69293e94f25");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "68.10.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("places.history.expiration.transient_current_max_pages", 87822);
user_pref("security.sandbox.plugin.tempDirSuffix", "413f0e61-504d-4605-92b7-306fd9ca2a6d");
user_pref("services.blocklist.pinning.checked", 1600971578);
user_pref("services.settings.clock_skew_seconds", -737);
user_pref("services.settings.last_etag", "\"1600905679357\"");
user_pref("services.settings.last_update_seconds", 1600971578);
user_pref("services.settings.main.hijack-blocklists.last_check", 1600971578);
user_pref("services.settings.main.language-dictionaries.last_check", 1600971578);
user_pref("services.settings.main.sites-classification.last_check", 1600971578);
user_pref("services.settings.security.onecrl.checked", 1600971578);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.telemetry.cachedClientID", "a0500f02-1fd5-4c47-80b4-b588b7225a4f");
user_pref("toolkit.telemetry.prompted", 2);
