// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.startupRolloutPrefs.doh-rollout.enabled", true);
user_pref("app.normandy.startupRolloutPrefs.doh-rollout.profileCreationThreshold", "1896163212345");
user_pref("app.normandy.startupRolloutPrefs.extensions.blocklist.useMLBF", true);
user_pref("app.normandy.startupRolloutPrefs.extensions.blocklist.useMLBF.stashes", true);
user_pref("app.normandy.user_id", "35741b83-76a1-48d5-abee-8aba6e04bdb1");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1600970707);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1600970685);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1600971955);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1600971798);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 7420);
user_pref("browser.cache.disk.capacity", 337920);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.lastDir", "/home/marianab/Downloads");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1600970676);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{b7255ebf-60cc-486b-be9d-12bd957750fa}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1600970682772");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1600974282772");
user_pref("browser.search.region", "US");
user_pref("browser.search.useDBForOrder", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200720193547");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1600971955");
user_pref("browser.slowStartup.averageTime", 1707);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20200720193547");
user_pref("browser.startup.homepage_override.mstone", "79.0");
user_pref("browser.startup.lastColdStartupCheck", 1600971954);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1600970681175");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "79.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.mode", 2);
user_pref("doh-rollout.self-enabled", true);
user_pref("doh-rollout.skipHeuristicsCheck", false);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "22ca7e9cef2e4e87b0658de1b19c63ff");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200720193547");
user_pref("extensions.lastAppVersion", "79.0");
user_pref("extensions.lastPlatformVersion", "79.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"f2ab05db-ce64-4ae2-881d-5990fead2596\",\"formautofill@mozilla.org\":\"47ef1234-e32e-4f24-87d0-a1f8ce72b0d6\",\"screenshots@mozilla.org\":\"53157c23-891e-4bdb-af05-96a6eeb929d1\",\"webcompat-reporter@mozilla.org\":\"1d171184-b52b-4b3a-aab4-7bbed4a62753\",\"webcompat@mozilla.org\":\"2b3dbfcf-aac3-4fb9-a6b1-1a86491c3bb7\",\"default-theme@mozilla.org\":\"a50b2492-8d80-4da0-83b3-e7c395c536e1\",\"google@search.mozilla.org\":\"e6116618-f47c-45fa-a887-e2328fc1794a\",\"amazondotcom@search.mozilla.org\":\"6bd1f16e-90b5-49b3-b7e5-be41589c7e0f\",\"wikipedia@search.mozilla.org\":\"4700edc2-d2bb-4a05-842f-8c21904c6cb0\",\"bing@search.mozilla.org\":\"9b31d639-0730-4aba-bade-96bc1f20a966\",\"ddg@search.mozilla.org\":\"b00e2215-bbec-4f6b-8638-6346dcab96ba\",\"ebay@search.mozilla.org\":\"c22791a9-335f-4439-9740-a3e5b1ffd569\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 88418);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "433928c6-87ca-4d9c-92c1-a584bfd0f620");
user_pref("security.sandbox.plugin.tempDirSuffix", "5cdb3ba4-ee46-4015-98b7-10d19759987c");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1600971953);
user_pref("toolkit.telemetry.cachedClientID", "148f0ae8-b81d-42ee-9b0e-6306989e5a96");
user_pref("toolkit.telemetry.previousBuildID", "20200720193547");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
